services:
  sql:
    image: postgres:latest
    # expose:
    #   - "5432"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

  server:
    # image: node:20
    build: .
    ports:
      - "${PORT}:${PORT}"
    restart: always
    environment:
      PORT: ${PORT}
    # working_dir: /opt/combat-classifieds
    # volumes:
    #   - ./combat-classifieds:/opt/combat-classifieds
    # command: 'npm ci && npm run build && npm start'
